language: generic

# Ubuntu Trusty is required for getting Python3 PIP setup working without too
# much pain. The Precise images don't have a python3-pip package.
dist: trusty
sudo: required

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qq python python3 python-pip python-setuptools python3-setuptools python3-pip
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  - sudo pip install neovim
  - sudo pip3 install neovim
  - mkdir deps
  - cd deps && git clone --depth 1 -q https://github.com/google/vroom.git && cd vroom && python3 setup.py build && sudo python3 setup.py install && cd ../..

script: ./run_tests.sh

